--- 
- 
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
  
############################################
# Install Samba
###########################################

      - name: Install Samba
        apt:
          name: samba
          state: present

      - name: Update smb.conf
        blockinfile:
          dest: "/etc/samba/smb.conf"
          block: |
           [pi]
           path = /home/pi
           only guest = no
           browsable = yes
           writeable = yes
           create mask = 0777
           directory mask = 0777
           public = yes
  
############################################
# Install Exiftool
###########################################

      - name: Install Exiftool
        apt:
          name: libimage-exiftool-perl
          state: present

############################################
# Pull gonet Repo from github, copy to /tools/Camera. and set ownership and permissions
###########################################

      - name: Get gonet4 repo from GitHub
        git: 
          dest: /home/pi/Tools/git_repo
          repo: "https://github.com/Wied58/gonet4.git"
          update: yes
          force: yes
          depth: 5
          version: "main"

      - name: Change owership and permissions
        file:
           path: /home/pi/Tools/git_repo
           state: directory
           owner: pi 
           group: pi
           # when specifying mode using octal numbers, add a leading 0
           mode: 0755
           recurse: yes

      - name: Copy gonet4.py from git_repo to Camera
        copy:
          src: /home/pi/Tools/git_repo/
          dest: /home/pi/Tools/Camera/
          owner: pi
          group: pi
          mode: 0775

      - name: Delete content & directory
        file:
          state: absent
          path: /home/pi/Tools/git_repo/

############################################
# Pull FectGPS  Repo from github, copy to /tools/Camera. and set ownership and permissions
###########################################

      - name: Get FetchGPS repo from GitHub
        git: 
          dest: /home/pi/Tools/git_repo
          repo: "https://github.com/Wied58/FetchGPS.git"
          update: yes
          force: yes
          depth: 5
          version: "main"

      - name: Change owership and permissions
        file:
           path: /home/pi/Tools/git_repo
           state: directory
           owner: pi 
           group: pi
           # when specifying mode using octal numbers, add a leading 0
           mode: 0755
           recurse: yes

      - name: Copy gonet4.py from git_repo to Camera
        copy:
          src: /home/pi/Tools/git_repo/
          dest: /home/pi/Tools/FetchGPS/
          owner: pi
          group: pi
          mode: 0775

      - name: Delete content & directory
        ansible.builtin.file:
          state: absent
          path: /home/pi/Tools/git_repo/

############################################
# Set the version number to git hash
###########################################

      - name: Ansible register variable basic example
        #shell: "git --git-dir /home/pi/Tools/git_repo/.git log --pretty=oneline --decorate | head -1 | awk '{print substr($1,1,5)}'"
        shell: echo "21."`git --git-dir /home/pi/Tools/git_repo/.git log --pretty=oneline --decorate | head -1 | awk '{print substr($1,1,5)}'`
        args:
          #chdir: "/home/pi/Tools/Version"
        register: new_version
   
      - debug:
          var: new_version.stdout


      - name: empty dest directory 
        file:
          state: absent
          path: /home/pi/Tools/Version/
      
      - name: recreate directory 
        file:
          state: directory
          path: /home/pi/Tools/Version/
          owner: pi
          group: pi
          mode: 0777
      
      - name: ensure file exists
        copy:
          content: ""
          dest: "/home/pi/Tools/Version/{{ new_version.stdout }}"
          force: yes
          owner: pi
          group: pi
          mode: 0755



############################################
# cron stuff
###########################################

        
      - name: comment out gonet cron job
        cron:
          name: "gonet"
          job: "*/5 * * * * python3 /home/pi/Tools/Camera/gonet4.py &"
          state: present
          disabled: True

      - name: Comment out cron replacement in rc.loca
        replace:
          #dest: /etc/rc.local
          dest: /home/pi/Tools/Autostart/Startup.sh
          regexp: "su pi -c 'crontab /home/pi/Tools/Crontab/CronBackup.txt'"
          replace: "#su pi -c 'crontab /home/pi/Tools/Crontab/CronBackup.txt'"


############################################
# .bashrc stuff
###########################################

      - name: Update .bashrc
        blockinfile: 
           dest: "/home/pi/.bashrc"
           block: |
            export EDITOR=/usr/bin/vi
            set -o vi 
   

